/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import sa.controller.AlumnoController;
import sa.model.to.AlumnoTO;
import sa.model.to.CarreraTO;

/**
 *
 * @author Dave
 */
public class AlumnoView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * @param controller
     */
    public AlumnoView(AlumnoController controller) {
        initComponents();
        jTAAlumnos.getSelectionModel().addListSelectionListener(e -> setAlumnoToView(controller.getAlumno(getSelectedAlumno())));
        jCBCarrera.setModel(controller.getModelCarreras());
        jBtnRegistrar.addActionListener((e) -> controller.createAlumno(getAlumnoFromView()));
        jBtnModificar.addActionListener(e -> controller.updateAlumno(getAlumnoFromView()));
        jBtnEliminar.addActionListener(e -> controller.deleteAlumno(getAlumnoFromView()));
        jBtnBuscar.addActionListener(e -> controller.busarTodos(jTAAlumnos));
    }
    
    private AlumnoTO getAlumnoFromView(){
        return new AlumnoTO(
                jTFNumeroControl.getText().trim(), 
                jTFNombres.getText().trim(), 
                jTFAPaterno.getText().trim(), 
                jTFAMaterno.getText().trim(), 
                Integer.parseInt(String.valueOf(jCBSemestre.getSelectedItem())), 
                new CarreraTO(String.valueOf(jCBCarrera.getSelectedItem()), null),
                new byte[10]
        );
    }
    
    private String getSelectedAlumno(){
        int selectedRow = jTAAlumnos.getSelectedRow();
        if(selectedRow != -1)
            return String.valueOf(jTAAlumnos.getValueAt(selectedRow, 0));
        return null;
    }

    private void setAlumnoToView(AlumnoTO alumno){
        if(alumno == null)
            return;
        jTFNumeroControl.setText(alumno.getNumeroControl());
        jTFNombres.setText(alumno.getNombres());
        jTFAPaterno.setText(alumno.getApellidoPaterno());
        jTFAMaterno.setText(alumno.getApellidoMaterno());
        jCBSemestre.setSelectedItem(alumno.getSemestre());
        jCBCarrera.setSelectedItem(alumno.getCarrera().getIdCarrera());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPForm = new javax.swing.JPanel();
        jPDataForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNumeroControl = new javax.swing.JTextField();
        jTFNombres = new javax.swing.JTextField();
        jTFAPaterno = new javax.swing.JTextField();
        jTFAMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBSemestre = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCBCarrera = new javax.swing.JComboBox<>();
        jPControlsForm = new javax.swing.JPanel();
        jBtnRegistrar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();
        jPResuts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Alumno", 2, 1));
        jPForm.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Numero de Control");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jTFNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombresActionPerformed(evt);
            }
        });

        jLabel5.setText("Semestre");

        jCBSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel6.setText("Carrera");

        javax.swing.GroupLayout jPDataFormLayout = new javax.swing.GroupLayout(jPDataForm);
        jPDataForm.setLayout(jPDataFormLayout);
        jPDataFormLayout.setHorizontalGroup(
            jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDataFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDataFormLayout.createSequentialGroup()
                        .addComponent(jTFAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPDataFormLayout.createSequentialGroup()
                        .addComponent(jTFNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jCBSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFAPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jCBCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPDataFormLayout.setVerticalGroup(
            jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDataFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTFAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDataFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCBSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCBCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPForm.add(jPDataForm, java.awt.BorderLayout.CENTER);

        jPControlsForm.setLayout(new java.awt.GridLayout(4, 1));

        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });
        jPControlsForm.add(jBtnRegistrar);

        jBtnModificar.setText("Modificar");
        jPControlsForm.add(jBtnModificar);

        jBtnEliminar.setText("Eliminar");
        jPControlsForm.add(jBtnEliminar);

        jBtnBuscar.setText("Buscar");
        jPControlsForm.add(jBtnBuscar);

        jPForm.add(jPControlsForm, java.awt.BorderLayout.EAST);

        getContentPane().add(jPForm, java.awt.BorderLayout.NORTH);

        jPResuts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Alumnos", 2, 1));
        jPResuts.setLayout(new java.awt.GridLayout(1, 0));

        jTAAlumnos.setAutoCreateRowSorter(true);
        jTAAlumnos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTAAlumnos);

        jPResuts.add(jScrollPane1);

        getContentPane().add(jPResuts, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jTFNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JComboBox<String> jCBCarrera;
    private javax.swing.JComboBox<String> jCBSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPControlsForm;
    private javax.swing.JPanel jPDataForm;
    private javax.swing.JPanel jPForm;
    private javax.swing.JPanel jPResuts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAAlumnos;
    private javax.swing.JTextField jTFAMaterno;
    private javax.swing.JTextField jTFAPaterno;
    private javax.swing.JTextField jTFNombres;
    private javax.swing.JTextField jTFNumeroControl;
    // End of variables declaration//GEN-END:variables

}
