/* 
 * The MIT License
 *
 * Copyright 2017 David Rodríguez <duvid9320@gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package sa.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import sa.model.to.InstructorTO;

/**
 *
 * @author dave
 */
public class InstructorView extends javax.swing.JFrame {
    private InstructorTO instructor;
    
    public InstructorView() {
        initComponents();
        instructor = new InstructorTO();
    }
    
    public void setNombresInstructor(){
        instructor.setNombres(jTFNombresInstructor.getText().trim());
    }
    
    public void setGradoInstructor(){
        instructor.setGrado(jTAGradoInstructor.getText().trim());
    }
    
    public void setIdInstructor(){
        instructor.setIdInstructor(getIdInstructor());
    }
    
    public String getIdInstructor(){
        return jTFIdInstructor.getText().trim();
    }
    
    public void setApellidosInstructor(){
        instructor.setApellidos(jTFApellidosInstructor.getText().trim());
    }

    public InstructorTO getInstructor() {
        return instructor;
    }

    public void setInstructor(InstructorTO instructor) {
        this.instructor = instructor;
    }

    public JButton getjBtnBuscarInstructores() {
        return jBtnBuscarInstructores;
    }

    public JButton getjBtnEliminarInstructor() {
        return jBtnEliminarInstructor;
    }

    public JButton getjBtnModificarInstructor() {
        return jBtnModificarInstructor;
    }

    public JButton getjBtnRegistrarInstructor() {
        return jBtnRegistrarInstructor;
    }

    public JTextArea getjTAGradoInstructor() {
        return jTAGradoInstructor;
    }

    public JTable getjTAQueryInstructores() {
        return jTAQueryInstructores;
    }

    public JTextField getjTFApellidosInstructor() {
        return jTFApellidosInstructor;
    }

    public JTextField getjTFIdInstructor() {
        return jTFIdInstructor;
    }

    public JTextField getjTFNombresInstructor() {
        return jTFNombresInstructor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFormInstructor = new javax.swing.JPanel();
        jPFormControls = new javax.swing.JPanel();
        jBtnRegistrarInstructor = new javax.swing.JButton();
        jBtnModificarInstructor = new javax.swing.JButton();
        jBtnEliminarInstructor = new javax.swing.JButton();
        jBtnBuscarInstructores = new javax.swing.JButton();
        jPFormFields = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNombresInstructor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFApellidosInstructor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAGradoInstructor = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTFIdInstructor = new javax.swing.JTextField();
        jPQueryResults = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAQueryInstructores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPFormInstructor.setLayout(new java.awt.BorderLayout());

        jPFormControls.setLayout(new java.awt.GridLayout(4, 1));

        jBtnRegistrarInstructor.setText("Registrar");
        jBtnRegistrarInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarInstructorActionPerformed(evt);
            }
        });
        jPFormControls.add(jBtnRegistrarInstructor);

        jBtnModificarInstructor.setText("Modificar");
        jPFormControls.add(jBtnModificarInstructor);

        jBtnEliminarInstructor.setText("Eliminar");
        jPFormControls.add(jBtnEliminarInstructor);

        jBtnBuscarInstructores.setText("Buscar");
        jPFormControls.add(jBtnBuscarInstructores);

        jPFormInstructor.add(jPFormControls, java.awt.BorderLayout.LINE_END);

        jPFormFields.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Instructor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Nombres");

        jTFNombresInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombresInstructorActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellidos");

        jLabel3.setText("Grado");

        jTAGradoInstructor.setColumns(20);
        jTAGradoInstructor.setRows(5);
        jScrollPane1.setViewportView(jTAGradoInstructor);

        jLabel4.setText("Id");

        javax.swing.GroupLayout jPFormFieldsLayout = new javax.swing.GroupLayout(jPFormFields);
        jPFormFields.setLayout(jPFormFieldsLayout);
        jPFormFieldsLayout.setHorizontalGroup(
            jPFormFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFormFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFormFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFormFieldsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTFIdInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNombresInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFApellidosInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(jPFormFieldsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPFormFieldsLayout.setVerticalGroup(
            jPFormFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFormFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFormFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombresInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFApellidosInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFIdInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPFormFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPFormInstructor.add(jPFormFields, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPFormInstructor, java.awt.BorderLayout.NORTH);

        jPQueryResults.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Instructores Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPQueryResults.setLayout(new java.awt.GridLayout(1, 0));

        jTAQueryInstructores.setAutoCreateRowSorter(true);
        jTAQueryInstructores.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTAQueryInstructores);

        jPQueryResults.add(jScrollPane2);

        getContentPane().add(jPQueryResults, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombresInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombresInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombresInstructorActionPerformed

    private void jBtnRegistrarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegistrarInstructorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarInstructores;
    private javax.swing.JButton jBtnEliminarInstructor;
    private javax.swing.JButton jBtnModificarInstructor;
    private javax.swing.JButton jBtnRegistrarInstructor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPFormControls;
    private javax.swing.JPanel jPFormFields;
    private javax.swing.JPanel jPFormInstructor;
    private javax.swing.JPanel jPQueryResults;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAGradoInstructor;
    private javax.swing.JTable jTAQueryInstructores;
    private javax.swing.JTextField jTFApellidosInstructor;
    private javax.swing.JTextField jTFIdInstructor;
    private javax.swing.JTextField jTFNombresInstructor;
    // End of variables declaration//GEN-END:variables

}
